config/routes.rb
Rails.application.routes.draw do
  resources :rvjs
  devise_for :users
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "services"=>"servic#services"
  # get "allemp"=>"employees#allemp"
  # get "new"=>"employees#new"
  # post 'emp' => "employees#create"
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
	def name
		"#{first_name} #{last_name}"
	end
end

app/models/rvj.rb
class Rvj < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController<ApplicationController
	def index
		@employees=Employee.all
	end
	def new
		@employee=Employee.new
	end

	def create
		@employee=Employee.new(first_name: params[:employee][:first_name],last_name: params[:employee][:last_name],email: params[:employee][:email],salary: params[:employee][:salary])
		if @employee.save
			redirect_to employees_path
		else
			render :new
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/rvjs_controller.rb
class RvjsController < ApplicationController
  before_action :set_rvj, only: %i[ show edit update destroy ]

  # GET /rvjs or /rvjs.json
  def index
    @rvjs = Rvj.all
  end

  # GET /rvjs/1 or /rvjs/1.json
  def show
  end

  # GET /rvjs/new
  def new
    @rvj = Rvj.new
  end

  # GET /rvjs/1/edit
  def edit
  end

  # POST /rvjs or /rvjs.json
  def create
    @rvj = Rvj.new(rvj_params)

    respond_to do |format|
      if @rvj.save
        format.html { redirect_to rvj_url(@rvj), notice: "Rvj was successfully created." }
        format.json { render :show, status: :created, location: @rvj }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rvj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rvjs/1 or /rvjs/1.json
  def update
    respond_to do |format|
      if @rvj.update(rvj_params)
        format.html { redirect_to rvj_url(@rvj), notice: "Rvj was successfully updated." }
        format.json { render :show, status: :ok, location: @rvj }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rvj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rvjs/1 or /rvjs/1.json
  def destroy
    @rvj.destroy

    respond_to do |format|
      format.html { redirect_to rvjs_url, notice: "Rvj was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rvj
      @rvj = Rvj.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rvj_params
      params.require(:rvj).permit(:title, :block)
    end
end

app/controllers/servic_controller.rb
class ServicController < ApplicationController
	def services
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rvjs_helper.rb
module RvjsHelper
end

app/views/employees/allemp.html.erb
<nav class="navbar navbar-expand-lg navbar-light p-4">
  <div class="container-fluid">
    <div class="container">
    <a class="navbar-brand" href="/">
      <%# <img src="rvj_logo.png" alt="" width="30" height="24"> %>
      <%= image_tag 'rvj_logo.png',width:"150" ,height:"75"%>
    </a>
  </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/services">SERVICES</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="allemp">EMP_DATA</a>
        </li>
        
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container text-center">
  <div class="card p-2">
    <h1 class="text-danger">Employees Data</h1>
  </div>



  <div class="card mt-3">
    <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Salary</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |val|%>
      <tr>
        <th scope="row"><%= val.id%></th>
        <td><%= val.first_name%></td>
        <td><%= val.email%></td>
        <td><%= val.salary%></td>
      </tr>
      <% end%>
    </tbody>
  </table>
  </div>
</div>

app/views/employees/index.html.erb
<div class="card">

  <div class="card-body">
    <h1 class="text-center">Employee Data</h1>
  </div>

<a href="/employees/new" class="btn btn-outline-primary col-lg-2 m-2">New Employee</a>

<div class="col-lg-12">
  <div class="card-body">
    <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Email</th>
        <th>Salary</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |data|%>
      <tr>
        <td><%= data.id%></td>
        <td><%= data.name%></td>
        <td><%= data.email%></td>
        <td><%= data.salary%></td>
      </tr>
      <% end%>
    </tbody>
  </table>
  </div>
</div>

</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
	<div class="card rounder-0 m-5">
		<div class="card-body">
			<h1 class="text-center">Employees new data insert.</h1>
		</div>
	</div>
	<%= form_with model: @employee do |form|%>
		<div class="row">
			<div class="col-lg-5 m-4">
				<div class="form-group m-4">
					<%= form.label :first_name, class: 'mb-2'%>
					<%= form.text_field :first_name, class: 'form-control form-control-lg'%>
				</div>
			</div>
			<div class="col-lg-5 m-4">
				<div class="form-group m-4">
					<%= form.label :last_name, class: 'mb-2'%>
					<%= form.text_field :last_name, class: 'form-control form-control-lg'%>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-5 m-4">
				<div class="form-group m-4">
					<%= form.label :email, class: 'mb-2'%>
					<%= form.text_field :email, class: 'form-control form-control-lg'%>
				</div>
			</div>
			<div class="col-lg-5 m-4">
				<div class="form-group m-4">
					<%= form.label :salary, class: 'mb-2'%>
					<%= form.text_field :salary, class: 'form-control form-control-lg'%>
				</div>
			</div>
		</div>
		<div class="col-lg-12 m-4">
			<div class="form-group m-4">
				<%= form.submit class:'btn-lg btn-primary' %>
				<%= link_to "back to student", employees_path, class:"btn btn-outline-primary btn-lg"%>
			</div>
		</div>
	<% end%>
</div>

app/views/home/index.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <h3 class="text-center col-lg-4 bg-secondary tran rounded-2 text-light">#WELCOME TO RVJ INFOTECH</h3>
</div>
<div class="container mt-5 d-flex justify-content-center ">
  <h1 class="text-center font-size-85">Meet RVJ INFOTECH, Your<br>
Technology Partner</h1>
</div>
<div class="container d-flex justify-content-center mt-1">
  <p class="font-size-45">It's crafted with the latest trend of design & coded with all<br>
modern approaches. Start growing your business with us</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RVJ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style type="text/css">
      .font-size-85{
        font-size: 85px;
      }
      .font-size-45{
        font-size: 29px;
      }
    </style>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background: rgb(255, 255, 205, 0.2);">
    <%= render "shere/nav"%>
    <%= link_to "Rvj blocks",rvjs_path,class: "btn btn-dark btn-lg m-4"%>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/rvjs/_form.html.erb
<%= form_with(model: rvj) do |form| %>
  <% if rvj.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rvj.errors.count, "error") %> prohibited this rvj from being saved:</h2>

      <ul>
        <% rvj.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :block, style: "display: block" %>
    <%= form.text_field :block %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rvjs/_rvj.html.erb
<div id="<%= dom_id rvj %>">
  <p>
    <strong>Title:</strong>
    <%= rvj.title %>
  </p>

  <p>
    <strong>Block:</strong>
    <%= rvj.block %>
  </p>

</div>

app/views/rvjs/edit.html.erb
<h1>Editing rvj</h1>

<%= render "form", rvj: @rvj %>

<br>

<div>
  <%= link_to "Show this rvj", @rvj %> |
  <%= link_to "Back to rvjs", rvjs_path %>
</div>

app/views/rvjs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rvjs</h1>

<div id="rvjs">
  <% @rvjs.each do |rvj| %>
    <%= render rvj %>
    <p>
      <%= link_to "Show this rvj", rvj %>
    </p>
  <% end %>
</div>

<%= link_to "New rvj", new_rvj_path %>

app/views/rvjs/new.html.erb
<h1>New rvj</h1>

<%= render "form", rvj: @rvj %>

<br>

<div>
  <%= link_to "Back to rvjs", rvjs_path %>
</div>

app/views/rvjs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rvj %>

<div>
  <%= link_to "Edit this rvj", edit_rvj_path(@rvj) %> |
  <%= link_to "Back to rvjs", rvjs_path %>

  <%= button_to "Destroy this rvj", @rvj, method: :delete %>
</div>

app/views/servic/services.html.erb
<div class="container d-flex justify-content-center">
  <label class="text-center text-primary bg-light p-2 rounded-2">#SERVICES</label>
</div>
<div class="container d-flex justify-content-center mt-2">
  <h1>What We do?</h1>
</div>
<div class="container d-flex justify-content-center mt-2">
  <p>We have extremely experienced and skilled dedicated developers who are experts in various<br> technologies and tools. Any technology you choose, our team will deliver best results.</p>
</div>


<div class="container d-flex justify-content-between mt-4">
  

<div class="card" style="width: 18rem;">
  <div class="container d-flex justify-content-center mt-2">
    <i class="fa fa-users font-size-45"></i>
  </div>
  <div class="card-body" style="background: rgb(255, 255, 205, 0.2);">
    <h5 class="card-title">Web Development</h5>
    <p class="card-text">Our highly qualified & experienced developers' team delivers highly customized web applications to our clients.</p>
 
  </div>
</div>

  
<div class="card" style="width: 18rem;">
  <div class="container d-flex justify-content-center mt-2">
    <i class="fa fa-mobile font-size-45"></i>
  </div>
  <div class="card-body" style="background: rgb(255, 255, 205, 0.2);">
    <h5 class="card-title">Mobile Development</h5>
    <p class="card-text">We offer a full cycle of application design, integration and management services.</p>
 
  </div>
</div>


  

<div class="card" style="width: 18rem;">
  <div class="container d-flex justify-content-center mt-2">
    <i class="fa fa-home font-size-45"></i>
  </div>
  <div class="card-body" style="background: rgb(255, 255, 205, 0.2);">
    <h5 class="card-title">Application Maintenance</h5>
    <p class="card-text">We ensure robust mechanisms and practices geared to your goals and are aimed at ensuring that applications are highly available and reliable.</p>

  </div>
</div>


  

<div class="card" style="width: 18rem;">
  <div class="container d-flex justify-content-center mt-2">
    <i class="fa fa-wrench font-size-45"></i>
  </div>
  <div class="card-body" style="background: rgb(255, 255, 205, 0.2);">
    <h5 class="card-title">Quality Assurance</h5>
    <p class="card-text">Our quality engineering team ensure high-quality standard of delivered product. We never compromise quality of our solutions.</p>
  
  </div>
</div>


</div>

app/views/shere/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light p-4">
  <div class="container-fluid">
    <div class="container">
    <a class="navbar-brand" href="/">
      <%# <img src="rvj_logo.png" alt="" width="30" height="24"> %>
      <%= image_tag 'rvj_logo.png',width:"150" ,height:"75"%>
    </a>
  </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/services">SERVICES</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="employees">EMP_DATA</a>
        </li>
        
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<nav class="navbar navbar-expand-lg navbar-light p-4">
  <%= link_to "Sin Up",new_user_registration_path,class: "nav-link"%>
    <%= link_to "Sin In",new_user_session_path,class: "nav-link"%>
    <%= link_to "Sin Out",destroy_user_session_path,method: :delete,class: "nav-link"%>
    <%= link_to "Edit Profile",edit_user_registration_path,class: "nav-link"%>
</nav>